/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_agents_get"];
        put?: never;
        /** Create Agent */
        post: operations["create_agent_api_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_api_agents__agent_id__get"];
        put?: never;
        post?: never;
        /** Delete Agent */
        delete: operations["delete_agent_api_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** Update Agent */
        patch: operations["update_agent_api_agents__agent_id__patch"];
        trace?: never;
    };
    "/api/agents/{agent_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Agent */
        post: operations["archive_agent_api_agents__agent_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Sessions */
        get: operations["list_agent_sessions_api_agents__agent_id__sessions_get"];
        put?: never;
        /**
         * Create Agent Session
         * @description Preferred path to start a session — the agent comes from the URL, so
         *     the body's `agent_id` (if any) is ignored.
         */
        post: operations["create_agent_session_api_agents__agent_id__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Schedules */
        get: operations["list_agent_schedules_api_agents__agent_id__schedules_get"];
        put?: never;
        /** Create Agent Schedule */
        post: operations["create_agent_schedule_api_agents__agent_id__schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Session */
        post: operations["import_session_api_sessions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Session */
        post: operations["reset_session_api_sessions__session_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Session
         * @description Archive the current session and return a fresh one.
         *
         *     Same name / working_dir / credential_id as the archived session,
         *     but a brand-new id and no message history. Schedules + bridge
         *     mappings repoint from old to new so user-facing automation
         *     continues uninterrupted.
         */
        post: operations["archive_session_api_sessions__session_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unarchive Session
         * @description Bring an archived session back as a live session.
         *
         *     Flips the DB row's `archived=0` and reloads it into the in-memory
         *     session map so writes (sendMessage, schedules, etc.) work again.
         */
        post: operations["unarchive_session_api_sessions__session_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Attachment */
        post: operations["upload_attachment_api_sessions__session_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Attachment */
        get: operations["download_attachment_api_sessions__session_id__attachments__attachment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/files/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * File Meta
         * @description Metadata-only sibling of /files.
         *
         *     The dialog hits this first to decide which renderer to mount and
         *     whether to skip the bytes fetch entirely (e.g. for an oversized
         *     file, we show the error inline rather than streaming kilobytes
         *     that will never render). Same security path as /files.
         */
        get: operations["file_meta_api_sessions__session_id__files_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_api_sessions__session_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/bg-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bg Tasks
         * @description All bg tasks for a session, most-recent first. Used by the
         *     sidebar / chip popover. Includes finished tasks so users can scroll
         *     back through history.
         */
        get: operations["list_bg_tasks_api_sessions__session_id__bg_tasks_get"];
        put?: never;
        /**
         * Start Bg Task
         * @description Start a new background task. Called by the bg MCP server.
         *
         *     Returns the freshly-created task row so the MCP tool can echo the
         *     task_id back to the model. The subprocess is already running by the
         *     time this returns — callers don't wait for completion.
         */
        post: operations["start_bg_task_api_sessions__session_id__bg_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/bg-tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bg Task */
        get: operations["get_bg_task_api_sessions__session_id__bg_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/bg-tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Bg Task
         * @description Best-effort cancel. Returns {cancelled: bool}; cancelled=False
         *     means the task wasn't currently running (already finished, or
         *     server restarted and lost the in-memory handle).
         */
        post: operations["cancel_bg_task_api_sessions__session_id__bg_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Question
         * @description Called by the MCP server. Creates a pending question, broadcasts
         *     the WS event so the frontend renders the form, returns the
         *     question_id the MCP server should long-poll on.
         */
        post: operations["create_question_api_sessions__session_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/questions/{question_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wait For Answer
         * @description MCP-server-facing long-poll. Returns when the user (or the
         *     session-level auto-answer timeout) submits. 408 on per-call
         *     timeout — the MCP server should loop and retry.
         */
        get: operations["wait_for_answer_api_sessions__session_id__questions__question_id__answer_get"];
        put?: never;
        /**
         * Submit Answer
         * @description Frontend-facing. The user pressed submit; route into the
         *     session_manager which formats the answer, persists the chat
         *     entry, broadcasts the question_answer WS event, and sets the
         *     Event that wakes the MCP server's long-poll.
         */
        post: operations["submit_answer_api_sessions__session_id__questions__question_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Schedules */
        get: operations["list_schedules_api_schedules_get"];
        put?: never;
        /**
         * Create Schedule
         * @description Create a schedule. Prefer `agent_id`; `session_id` is accepted for one
         *     release and resolved to the session's owning agent (agent-refactor.md
         *     §5.4).
         */
        post: operations["create_schedule_api_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Schedule */
        delete: operations["delete_schedule_api_schedules__schedule_id__delete"];
        options?: never;
        head?: never;
        /** Update Schedule */
        patch: operations["update_schedule_api_schedules__schedule_id__patch"];
        trace?: never;
    };
    "/api/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Credentials */
        get: operations["list_credentials_api_credentials_get"];
        put?: never;
        /** Create Credential */
        post: operations["create_credential_api_credentials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Credential */
        delete: operations["delete_credential_api_credentials__credential_id__delete"];
        options?: never;
        head?: never;
        /** Update Credential */
        patch: operations["update_credential_api_credentials__credential_id__patch"];
        trace?: never;
    };
    "/api/credentials/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oauth Start */
        post: operations["oauth_start_api_credentials_oauth_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/oauth/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Oauth Complete
         * @description Submit the code copied from the OAuth callback, exchange it for a
         *     long-lived API key via Anthropic's OAuth + api-key endpoints, and
         *     persist the credential.
         *
         *     Two completion shapes from the orchestrator:
         *       - `session.token` set → Console org user with a fresh sk-ant- key.
         *         Stored as auth_type=oauth, no expiry tracking needed.
         *       - `session.oauth_tokens` set → Pro/Max subscriber whose token can't
         *         mint an API key. We store the full OAuthTokenSet as JSON, with
         *         token_expires_at populated so the resolver knows when to refresh.
         */
        post: operations["oauth_complete_api_credentials_oauth_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/oauth/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Oauth Cancel
         * @description Abort an in-flight login (kills the subprocess). Idempotent.
         */
        post: operations["oauth_cancel_api_credentials_oauth_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifiers */
        get: operations["list_notifiers_api_notifiers_get"];
        put?: never;
        /** Create Notifier */
        post: operations["create_notifier_api_notifiers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifiers/{notifier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Notifier */
        delete: operations["delete_notifier_api_notifiers__notifier_id__delete"];
        options?: never;
        head?: never;
        /** Update Notifier */
        patch: operations["update_notifier_api_notifiers__notifier_id__patch"];
        trace?: never;
    };
    "/api/backends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Backends
         * @description Which AI backends are usable on this host (codex-backend.md §6.1).
         *     `claude-code` is always listed; `codex` appears only when its binary
         *     resolves on PATH.
         */
        get: operations["list_backends_api_backends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentCreate */
        AgentCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Avatar */
            avatar?: string | null;
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /** Model */
            model?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /**
             * Mcp Servers
             * @default [
             *       "ask",
             *       "bg",
             *       "viewer"
             *     ]
             */
            mcp_servers: string[];
            /**
             * Tool Allow
             * @default
             */
            tool_allow: string;
            /**
             * Tool Deny
             * @default
             */
            tool_deny: string;
        };
        /** AgentRead */
        AgentRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Avatar */
            avatar?: string | null;
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /** Model */
            model?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /**
             * Mcp Servers
             * @default []
             */
            mcp_servers: string[];
            /**
             * Tool Allow
             * @default
             */
            tool_allow: string;
            /**
             * Tool Deny
             * @default
             */
            tool_deny: string;
            /**
             * Is System
             * @default false
             */
            is_system: boolean;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Active Session Count
             * @default 0
             */
            active_session_count: number;
        };
        /** AgentUpdate */
        AgentUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Avatar */
            avatar?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Model */
            model?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /** Mcp Servers */
            mcp_servers?: string[] | null;
            /** Tool Allow */
            tool_allow?: string | null;
            /** Tool Deny */
            tool_deny?: string | null;
        };
        /**
         * AnswerItem
         * @description One entry in the frontend's answer submission. Mirrors the
         *     legacy WS answer_question payload so existing UI code keeps
         *     working.
         */
        AnswerItem: {
            /** Selected */
            selected?: string[] | null;
            /** Text */
            text?: string | null;
        };
        /**
         * AttachmentMetadata
         * @description Metadata for a user-uploaded file attached to a message.
         *
         *     Only what clients need to render the chip / fetch the file. The
         *     on-disk path lives in `server.attachments` and is derivable from
         *     `session_id + id` — we don't ship it to the client.
         */
        AttachmentMetadata: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
            /** Mime Type */
            mime_type: string;
        };
        /**
         * AuthType
         * @enum {string}
         */
        AuthType: "api_key" | "oauth";
        /**
         * BackendKind
         * @enum {string}
         */
        BackendKind: "claude-code" | "codex";
        /** Body_upload_attachment_api_sessions__session_id__attachments_post */
        Body_upload_attachment_api_sessions__session_id__attachments_post: {
            /** File */
            file: string;
        };
        /** CreateCredentialRequest */
        CreateCredentialRequest: {
            backend: components["schemas"]["BackendKind"];
            /** Label */
            label: string;
            /** @default api_key */
            auth_type: components["schemas"]["AuthType"];
            /** Secret */
            secret: string;
        };
        /** CreateNotifierRequest */
        CreateNotifierRequest: {
            type: components["schemas"]["NotifierType"];
            /** Label */
            label: string;
            /**
             * Config
             * @default {}
             */
            config: {
                [key: string]: unknown;
            };
        };
        /**
         * CreateQuestionRequest
         * @description Body for POST /questions. The schema mirrors the existing
         *     AskUserQuestion tool input so the model's call shape is unchanged.
         */
        CreateQuestionRequest: {
            /** Questions */
            questions: {
                [key: string]: unknown;
            }[];
        };
        /** CreateScheduleRequest */
        CreateScheduleRequest: {
            /** Name */
            name: string;
            /** Prompt */
            prompt: string;
            /** Interval Seconds */
            interval_seconds: number;
            /** Agent Id */
            agent_id?: string | null;
            /** Session Id */
            session_id?: string | null;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Name */
            name?: string | null;
            /** Working Dir */
            working_dir?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /** Agent Id */
            agent_id?: string | null;
            /** @default claude-code */
            backend: components["schemas"]["BackendKind"];
        };
        /**
         * CredentialInfo
         * @description Credential metadata returned to clients — never includes the secret.
         *
         *     Refresh-state fields (Steal Plan B-4 / B-5) are populated for OAuth
         *     providers that issue short-lived access tokens. Claude Code's
         *     long-lived `sk-ant-` key leaves them null today; they're here so the
         *     UI can render "needs reconnect" once a refresh-token provider lands
         *     without another schema/contract pump.
         */
        CredentialInfo: {
            /** Id */
            id: string;
            backend: components["schemas"]["BackendKind"];
            /** Label */
            label: string;
            auth_type: components["schemas"]["AuthType"];
            /** Created At */
            created_at: string;
            /** @default active */
            status: components["schemas"]["CredentialStatus"];
            /** Token Expires At */
            token_expires_at?: string | null;
            /**
             * Needs Reconnect
             * @default false
             */
            needs_reconnect: boolean;
            /** Last Refresh Error Code */
            last_refresh_error_code?: string | null;
        };
        /**
         * CredentialStatus
         * @enum {string}
         */
        CredentialStatus: "active" | "needs_reconnect";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportSessionRequest */
        ImportSessionRequest: {
            /**
             * Name
             * @default Imported Session
             */
            name: string;
            /** Working Dir */
            working_dir?: string | null;
            /** Claude Session Id */
            claude_session_id?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /** Agent Id */
            agent_id?: string | null;
            /** @default claude-code */
            backend: components["schemas"]["BackendKind"];
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["MessageContent"][];
        };
        /** MessageContent */
        MessageContent: {
            role: components["schemas"]["MessageRole"];
            /** Type */
            type: string;
            /** Content */
            content?: unknown;
            /** Tool Name */
            tool_name?: string | null;
            /** Tool Input */
            tool_input?: {
                [key: string]: unknown;
            } | null;
            /** Tool Use Id */
            tool_use_id?: string | null;
            /** Is Error */
            is_error?: boolean | null;
            /** Session Id */
            session_id?: string | null;
            /** Cost */
            cost?: number | null;
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["AttachmentMetadata"][];
            /** Seq */
            seq?: number | null;
        };
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "user" | "assistant" | "system" | "tool";
        /**
         * NotifierInfo
         * @description Notifier metadata returned to clients.
         *
         *     `config` is type-specific (e.g. webhook: `{"url": "..."}`). Clients
         *     treat it as opaque except for the keys they know how to render.
         */
        NotifierInfo: {
            /** Id */
            id: string;
            type: components["schemas"]["NotifierType"];
            /** Label */
            label: string;
            /**
             * Config
             * @default {}
             */
            config: {
                [key: string]: unknown;
            };
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Created At */
            created_at: string;
        };
        /**
         * NotifierType
         * @enum {string}
         */
        NotifierType: "webhook";
        /** OAuthCancelRequest */
        OAuthCancelRequest: {
            /** Login Id */
            login_id: string;
        };
        /** OAuthCompleteRequest */
        OAuthCompleteRequest: {
            /** Login Id */
            login_id: string;
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** OAuthStartRequest */
        OAuthStartRequest: {
            /** @default claude-code */
            backend: components["schemas"]["BackendKind"];
        };
        /** OAuthStartResponse */
        OAuthStartResponse: {
            /** Login Id */
            login_id: string;
            /** Device Url */
            device_url: string;
        };
        /** PendingQuestionInfo */
        PendingQuestionInfo: {
            /** Question Id */
            question_id: string;
            /** Questions */
            questions: {
                [key: string]: unknown;
            }[];
        };
        /** ScheduleInfo */
        ScheduleInfo: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id: string;
            /** Name */
            name: string;
            /** Prompt */
            prompt: string;
            /** Interval Seconds */
            interval_seconds: number;
            /** Enabled */
            enabled: boolean;
            /** Created At */
            created_at: string;
            /** Last Run At */
            last_run_at?: string | null;
        };
        /** SessionDetail */
        SessionDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Working Dir */
            working_dir: string;
            status: components["schemas"]["SessionStatus"];
            /** Created At */
            created_at: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /** Claude Session Id */
            claude_session_id?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /** Agent Id */
            agent_id?: string | null;
            /**
             * Origin
             * @default user
             */
            origin: string;
            /** @default claude-code */
            backend: components["schemas"]["BackendKind"];
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["MessageContent"][];
            /**
             * Pending Queue
             * @default []
             */
            pending_queue: string[];
            /**
             * Pending Questions
             * @default []
             */
            pending_questions: components["schemas"]["PendingQuestionInfo"][];
            /**
             * Next Message Seq
             * @default 0
             */
            next_message_seq: number;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Working Dir */
            working_dir: string;
            status: components["schemas"]["SessionStatus"];
            /** Created At */
            created_at: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /** Claude Session Id */
            claude_session_id?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /** Agent Id */
            agent_id?: string | null;
            /**
             * Origin
             * @default user
             */
            origin: string;
            /** @default claude-code */
            backend: components["schemas"]["BackendKind"];
            /**
             * Archived
             * @default false
             */
            archived: boolean;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "idle" | "running" | "waiting_approval";
        /** StartBgTaskRequest */
        StartBgTaskRequest: {
            /** Command */
            command: string;
            /** Description */
            description?: string | null;
        };
        /** SubmitAnswerRequest */
        SubmitAnswerRequest: {
            /** Answers */
            answers: components["schemas"]["AnswerItem"][];
        };
        /** UpdateCredentialRequest */
        UpdateCredentialRequest: {
            /** Label */
            label?: string | null;
            /** Secret */
            secret?: string | null;
        };
        /** UpdateNotifierRequest */
        UpdateNotifierRequest: {
            /** Label */
            label?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** UpdateScheduleRequest */
        UpdateScheduleRequest: {
            /** Name */
            name?: string | null;
            /** Prompt */
            prompt?: string | null;
            /** Interval Seconds */
            interval_seconds?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_api_agents_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_api_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_api_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_api_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_agent_api_agents__agent_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_sessions_api_agents__agent_id__sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_session_api_agents__agent_id__sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_schedules_api_agents__agent_id__schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_schedule_api_agents__agent_id__schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_session_api_sessions_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_session_api_sessions__session_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_session_api_sessions__session_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_session_api_sessions__session_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_attachment_api_sessions__session_id__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_attachment_api_sessions__session_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_attachment_api_sessions__session_id__attachments__attachment_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_meta_api_sessions__session_id__files_meta_get: {
        parameters: {
            query: {
                path: string;
                token?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_sessions__session_id__files_get: {
        parameters: {
            query: {
                path: string;
                token?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bg_tasks_api_sessions__session_id__bg_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_bg_task_api_sessions__session_id__bg_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartBgTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bg_task_api_sessions__session_id__bg_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_bg_task_api_sessions__session_id__bg_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_api_sessions__session_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wait_for_answer_api_sessions__session_id__questions__question_id__answer_get: {
        parameters: {
            query?: {
                timeout?: number;
            };
            header?: never;
            path: {
                session_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_sessions__session_id__questions__question_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedules_api_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"][];
                };
            };
        };
    };
    create_schedule_api_schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_schedule_api_schedules__schedule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_schedule_api_schedules__schedule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_credentials_api_credentials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfo"][];
                };
            };
        };
    };
    create_credential_api_credentials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_credential_api_credentials__credential_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_credential_api_credentials__credential_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_start_api_credentials_oauth_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_complete_api_credentials_oauth_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_cancel_api_credentials_oauth_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifiers_api_notifiers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifierInfo"][];
                };
            };
        };
    };
    create_notifier_api_notifiers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotifierRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifierInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_notifier_api_notifiers__notifier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notifier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_notifier_api_notifiers__notifier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notifier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotifierRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifierInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backends_api_backends_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
