/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Session */
        post: operations["import_session_api_sessions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Session */
        post: operations["reset_session_api_sessions__session_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Schedules */
        get: operations["list_schedules_api_schedules_get"];
        put?: never;
        /** Create Schedule */
        post: operations["create_schedule_api_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Schedule */
        delete: operations["delete_schedule_api_schedules__schedule_id__delete"];
        options?: never;
        head?: never;
        /** Update Schedule */
        patch: operations["update_schedule_api_schedules__schedule_id__patch"];
        trace?: never;
    };
    "/api/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Credentials */
        get: operations["list_credentials_api_credentials_get"];
        put?: never;
        /** Create Credential */
        post: operations["create_credential_api_credentials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Credential */
        delete: operations["delete_credential_api_credentials__credential_id__delete"];
        options?: never;
        head?: never;
        /** Update Credential */
        patch: operations["update_credential_api_credentials__credential_id__patch"];
        trace?: never;
    };
    "/api/credentials/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oauth Start */
        post: operations["oauth_start_api_credentials_oauth_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/oauth/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Oauth Complete
         * @description Submit the code copied from the OAuth callback, exchange it for a
         *     long-lived API key via Anthropic's OAuth + api-key endpoints, and
         *     persist the credential.
         */
        post: operations["oauth_complete_api_credentials_oauth_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/oauth/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Oauth Cancel
         * @description Abort an in-flight login (kills the subprocess). Idempotent.
         */
        post: operations["oauth_cancel_api_credentials_oauth_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthType
         * @enum {string}
         */
        AuthType: "api_key" | "oauth";
        /**
         * BackendKind
         * @enum {string}
         */
        BackendKind: "claude-code" | "codex";
        /** CreateCredentialRequest */
        CreateCredentialRequest: {
            backend: components["schemas"]["BackendKind"];
            /** Label */
            label: string;
            /** @default api_key */
            auth_type: components["schemas"]["AuthType"];
            /** Secret */
            secret: string;
        };
        /** CreateScheduleRequest */
        CreateScheduleRequest: {
            /** Session Id */
            session_id: string;
            /** Name */
            name: string;
            /** Prompt */
            prompt: string;
            /** Interval Seconds */
            interval_seconds: number;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Name
             * @default New Session
             */
            name: string;
            /** Working Dir */
            working_dir?: string | null;
            /** Credential Id */
            credential_id?: string | null;
        };
        /**
         * CredentialInfo
         * @description Credential metadata returned to clients — never includes the secret.
         *
         *     Refresh-state fields (Steal Plan B-4 / B-5) are populated for OAuth
         *     providers that issue short-lived access tokens. Claude Code's
         *     long-lived `sk-ant-` key leaves them null today; they're here so the
         *     UI can render "needs reconnect" once a refresh-token provider lands
         *     without another schema/contract pump.
         */
        CredentialInfo: {
            /** Id */
            id: string;
            backend: components["schemas"]["BackendKind"];
            /** Label */
            label: string;
            auth_type: components["schemas"]["AuthType"];
            /** Created At */
            created_at: string;
            /** @default active */
            status: components["schemas"]["CredentialStatus"];
            /** Token Expires At */
            token_expires_at?: string | null;
            /**
             * Needs Reconnect
             * @default false
             */
            needs_reconnect: boolean;
            /** Last Refresh Error Code */
            last_refresh_error_code?: string | null;
        };
        /**
         * CredentialStatus
         * @enum {string}
         */
        CredentialStatus: "active" | "needs_reconnect";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportSessionRequest */
        ImportSessionRequest: {
            /**
             * Name
             * @default Imported Session
             */
            name: string;
            /** Working Dir */
            working_dir?: string | null;
            /** Claude Session Id */
            claude_session_id?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["MessageContent"][];
        };
        /** MessageContent */
        MessageContent: {
            role: components["schemas"]["MessageRole"];
            /** Type */
            type: string;
            /** Content */
            content?: unknown;
            /** Tool Name */
            tool_name?: string | null;
            /** Tool Input */
            tool_input?: {
                [key: string]: unknown;
            } | null;
            /** Tool Use Id */
            tool_use_id?: string | null;
            /** Is Error */
            is_error?: boolean | null;
            /** Session Id */
            session_id?: string | null;
            /** Cost */
            cost?: number | null;
            /** Seq */
            seq?: number | null;
        };
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "user" | "assistant" | "system" | "tool";
        /** OAuthCancelRequest */
        OAuthCancelRequest: {
            /** Login Id */
            login_id: string;
        };
        /** OAuthCompleteRequest */
        OAuthCompleteRequest: {
            /** Login Id */
            login_id: string;
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** OAuthStartRequest */
        OAuthStartRequest: {
            /** @default claude-code */
            backend: components["schemas"]["BackendKind"];
        };
        /** OAuthStartResponse */
        OAuthStartResponse: {
            /** Login Id */
            login_id: string;
            /** Device Url */
            device_url: string;
        };
        /** PendingQuestionInfo */
        PendingQuestionInfo: {
            /** Question Id */
            question_id: string;
            /** Questions */
            questions: {
                [key: string]: unknown;
            }[];
        };
        /** ScheduleInfo */
        ScheduleInfo: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Name */
            name: string;
            /** Prompt */
            prompt: string;
            /** Interval Seconds */
            interval_seconds: number;
            /** Enabled */
            enabled: boolean;
            /** Created At */
            created_at: string;
            /** Last Run At */
            last_run_at?: string | null;
        };
        /** SessionDetail */
        SessionDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Working Dir */
            working_dir: string;
            status: components["schemas"]["SessionStatus"];
            /** Created At */
            created_at: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /** Claude Session Id */
            claude_session_id?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["MessageContent"][];
            /**
             * Pending Queue
             * @default []
             */
            pending_queue: string[];
            /**
             * Pending Questions
             * @default []
             */
            pending_questions: components["schemas"]["PendingQuestionInfo"][];
            /**
             * Next Message Seq
             * @default 0
             */
            next_message_seq: number;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Working Dir */
            working_dir: string;
            status: components["schemas"]["SessionStatus"];
            /** Created At */
            created_at: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /** Claude Session Id */
            claude_session_id?: string | null;
            /** Credential Id */
            credential_id?: string | null;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "idle" | "running" | "waiting_approval";
        /** UpdateCredentialRequest */
        UpdateCredentialRequest: {
            /** Label */
            label?: string | null;
            /** Secret */
            secret?: string | null;
        };
        /** UpdateScheduleRequest */
        UpdateScheduleRequest: {
            /** Name */
            name?: string | null;
            /** Prompt */
            prompt?: string | null;
            /** Interval Seconds */
            interval_seconds?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_session_api_sessions_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_session_api_sessions__session_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedules_api_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"][];
                };
            };
        };
    };
    create_schedule_api_schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_schedule_api_schedules__schedule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_schedule_api_schedules__schedule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_credentials_api_credentials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfo"][];
                };
            };
        };
    };
    create_credential_api_credentials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_credential_api_credentials__credential_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_credential_api_credentials__credential_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_start_api_credentials_oauth_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_complete_api_credentials_oauth_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_cancel_api_credentials_oauth_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
