/** Convenience re-exports of generated contract types.
 *
 * `contracts.ts` is auto-generated by `bun run generate:contracts`
 * (which dumps FastAPI's openapi.json and runs openapi-typescript).
 * Don't edit it directly. To pick up server-side schema changes:
 *
 *   cd web && bun run generate:contracts
 *
 * This wrapper renames `components["schemas"]["X"]` to bare `X` so the
 * rest of the frontend can `import type { SessionInfo } from "../api"`
 * without navigating the nested OpenAPI structure.
 */

import type { components } from "./contracts";

export type AttachmentMetadata = components["schemas"]["AttachmentMetadata"];
export type AuthType = components["schemas"]["AuthType"];
export type BackendKind = components["schemas"]["BackendKind"];
export type CredentialInfo = components["schemas"]["CredentialInfo"];
export type MessageContent = components["schemas"]["MessageContent"];
export type MessageRole = components["schemas"]["MessageRole"];
export type NotifierInfo = components["schemas"]["NotifierInfo"];
export type NotifierType = components["schemas"]["NotifierType"];
export type PendingQuestionInfo = components["schemas"]["PendingQuestionInfo"];
export type ScheduleInfo = components["schemas"]["ScheduleInfo"];
export type SessionDetail = components["schemas"]["SessionDetail"];
export type SessionInfo = components["schemas"]["SessionInfo"];
export type SessionStatus = components["schemas"]["SessionStatus"];

export type CreateCredentialRequest = components["schemas"]["CreateCredentialRequest"];
export type CreateNotifierRequest = components["schemas"]["CreateNotifierRequest"];
export type CreateScheduleRequest = components["schemas"]["CreateScheduleRequest"];
export type CreateSessionRequest = components["schemas"]["CreateSessionRequest"];
export type ImportSessionRequest = components["schemas"]["ImportSessionRequest"];
export type UpdateCredentialRequest = components["schemas"]["UpdateCredentialRequest"];
export type UpdateNotifierRequest = components["schemas"]["UpdateNotifierRequest"];
export type UpdateScheduleRequest = components["schemas"]["UpdateScheduleRequest"];
