#!/usr/bin/env python3
"""Generate the plans table in `docs/README.md` from the plans themselves.

`docs/plans/` mixed shipped designs, in-progress ones and superseded ones with
no way to tell them apart from the outside, and the hand-written list in
`docs/README.md` had drifted to 13 of 23 plans — the same failure mode as the
hand-maintained test inventory in `CLAUDE.md` (docs/plans/polish-2026-09.md §6
D2, §7 E1). So each plan states its own status on one machine-readable line
under its title:

    > **Status:** shipped — one line on what it is.

and this script renders them into the marked block in `docs/README.md`.
`--check` verifies the committed block matches, which is what
`scripts/check.sh` runs; a new plan therefore cannot be added without
appearing in the index.

Statuses: `shipped`, `in-progress`, `superseded by <plan>.md`.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLANS = ROOT / "docs" / "plans"
README = ROOT / "docs" / "README.md"

BEGIN = "<!-- BEGIN plans-index (generated by scripts/gen-docs-index.py) -->"
END = "<!-- END plans-index -->"

_STATUS_RE = re.compile(r"^> \*\*Status:\*\* (?P<status>[^—]+)—(?P<summary>.+)$")

# In-progress first: the question a reader has is "what is live and what is
# being built", and the answer to the second half is shorter and more urgent.
_ORDER = {"in-progress": 0, "shipped": 1}


def _rank(status: str) -> int:
    if status.startswith("superseded"):
        return 2
    return _ORDER.get(status, 3)


def read_plans() -> list[tuple[str, str, str, str]]:
    """`(filename, title, status, summary)` for every plan, in table order."""
    rows: list[tuple[str, str, str, str]] = []
    missing: list[str] = []
    for path in sorted(PLANS.glob("*.md")):
        lines = path.read_text().split("\n")
        title = lines[0].removeprefix("# ").strip() if lines[0].startswith("# ") else ""
        status = summary = ""
        for line in lines[1:8]:
            m = _STATUS_RE.match(line.strip())
            if m:
                status = m.group("status").strip()
                summary = m.group("summary").strip()
                break
        if not (title and status and summary):
            missing.append(path.name)
            continue
        rows.append((path.name, title, status, summary))
    if missing:
        raise SystemExit(
            "these plans have no `> **Status:** <status> — <summary>` line under "
            "their title:\n  " + "\n  ".join(missing)
        )
    rows.sort(key=lambda r: (_rank(r[2]), r[1].lower()))
    return rows


def render(rows: list[tuple[str, str, str, str]]) -> str:
    out = [BEGIN, "", "| Plan | Status | What |", "|---|---|---|"]
    for name, title, status, summary in rows:
        out.append(f"| [{title}](plans/{name}) | {status} | {summary} |")
    out += ["", END]
    return "\n".join(out)


def splice(readme: str, block: str) -> str:
    start, end = readme.find(BEGIN), readme.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"docs/README.md is missing the {BEGIN} / {END} markers the index "
            "goes between"
        )
    return readme[:start] + block + readme[end + len(END) :]


def main() -> int:
    check = "--check" in sys.argv[1:]
    current = README.read_text()
    wanted = splice(current, render(read_plans()))
    if check:
        if current == wanted:
            print("docs/README.md plans index is in sync")
            return 0
        print(
            "docs/README.md plans index is STALE — regenerate with:\n"
            "    .venv/bin/python scripts/gen-docs-index.py",
            file=sys.stderr,
        )
        return 1
    if current != wanted:
        README.write_text(wanted)
        print("docs/README.md plans index updated")
    else:
        print("docs/README.md plans index already current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
